name: Sync and merge upstream repository
on:
  schedule: 
  - cron: "0 8 * * *" #Runs at 8:00 UTC(5:00 in Korea) every day.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.0.0.b
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://github.com/BilliG-14/BilliG-FRONT.git
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: master
          # Branch to merge into downstream
          downstream_branch: master
          # GitHub Bot token
          token: ${{secrets.NEW_GITHUB_TOKEN}}
