name: 'Upstream Sync'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          ref:  master
          persist-credentials: false
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: master
          # REQUIRED 'target_repo_token' exactly like this!
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: https://github.com/BilliG-14/BilliG-FRONT.git
          upstream_repo_access_token: ${{ secrets.BILLIG_TOKEN }}

          # Set test_mode true to run tests instead of the true action!!
          test_mode: false
