name: Sync and merge upstream repository
on:
  schedule: 
  - cron: "0 8 * * *" #Runs at 8:00 UTC(5:00 in Korea) every day.
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:
 
jobs:
 sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    
    steps:
    # REQUIRED step
    # Step 1: run a standard checkout action, provided by github
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          ref:  master
          persist-credentials: false
          
    # REQUIRED step
    # Step 2: run the sync action       
      - name: Sync upstream changes
        id: sync
        uses: Gyuri092/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: master
          # REQUIRED 'target_repo_token' exactly like this!
          target_repo_token: ${{ secrets.BILLIG_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: Gyuri092/Fork-Sync-With-Upstream-action
          upstream_repo_access_token: ${{ secrets.NEW_GITHUB_TOKEN }}

          # Set test_mode true to run tests instead of the true action!!
          test_mode: false
